### ISSUE TITLE
Query: Is this library dead?

### ISSUE THREAD

**Issue by LukaszGrela** [constantoduol/JSONEditor#23]
Are you still maintaining this library or is it dead?

I'm asking as there are no recent updates and forking this repo and running `npm i` throws a lot of warnings:

```
> react-json-editor-viewer@1.0.7 prepare
> husky install

husky - Git hooks installed

added 1438 packages, and audited 1439 packages in 1m

122 vulnerabilities (12 low, 69 moderate, 32 high, 9 critical)

To address issues that do not require attention, run:
  npm audit fix

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.
```

and attempt to run `npm run start` yields following errors:

```
Compiled with warnings.

./src/demo/App.js
  Line 35:  Duplicate key 'borderLeft'  no-dupe-keys

Search for the keywords to learn more about each warning.
To ignore, add // eslint-disable-next-line to the line before.

.../JSONEditor/node_modules/watchpack/lib/chokidar.js:17
throw new Error(
^

Error: No version of chokidar is available. Tried chokidar@2 and chokidar@3.
You could try to manually install any chokidar version.
chokidar@3: Error: Cannot find module 'chokidar'
Require stack:
- .../JSONEditor/node_modules/watchpack/lib/chokidar.js
- .../JSONEditor/node_modules/watchpack/lib/DirectoryWatcher.js
- .../JSONEditor/node_modules/watchpack/lib/watcherManager.js
- .../JSONEditor/node_modules/watchpack/lib/watchpack.js
- .../JSONEditor/node_modules/webpack/lib/node/NodeWatchFileSystem.js
- .../JSONEditor/node_modules/webpack/lib/node/NodeEnvironmentPlugin.js
- .../JSONEditor/node_modules/webpack/lib/webpack.js
- .../JSONEditor/scripts/start.js
chokidar@2: Error: Cannot find module 'watchpack-chokidar2'
Require stack:
- .../JSONEditor/node_modules/watchpack/lib/chokidar.js
- .../JSONEditor/node_modules/watchpack/lib/DirectoryWatcher.js
- .../JSONEditor/node_modules/watchpack/lib/watcherManager.js
- .../JSONEditor/node_modules/watchpack/lib/watchpack.js
- .../JSONEditor/node_modules/webpack/lib/node/NodeWatchFileSystem.js
- .../JSONEditor/node_modules/webpack/lib/node/NodeEnvironmentPlugin.js
- .../JSONEditor/node_modules/webpack/lib/webpack.js
- .../JSONEditor/scripts/start.js

    at Object.<anonymous> (.../JSONEditor/node_modules/watchpack/lib/chokidar.js:17:7)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (.../JSONEditor/node_modules/watchpack/lib/DirectoryWatcher.js:9:16)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at WatcherManager.getDirectoryWatcher (.../JSONEditor/node_modules/watchpack/lib/watcherManager.js:14:25)
    at WatcherManager.watchFile (.../JSONEditor/node_modules/watchpack/lib/watcherManager.js:28:14)
```

**Comment by LukaszGrela** [comment]
that second error was resolvable with `npm update chokidar@latest`

**Comment by constantoduol** [comment]
I don't actively maintain this library. PRs are welcome
